[error] sbt.librarymanagement.ResolveException: Error downloading com.lightbend.cinnamon:cinnamon-prometheus-httpserver:2.13.2
[error]   Not found
[error]   Not found
[error]   not found: /home/victor/.ivy2/local/com.lightbend.cinnamon/cinnamon-prometheus-httpserver/2.13.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cinnamon/cinnamon-prometheus-httpserver/2.13.2/cinnamon-prometheus-httpserver-2.13.2.pom
[error] Error downloading com.lightbend.cinnamon:cinnamon-akka-stream_2.13:2.13.2
[error]   Not found
[error]   Not found
[error]   not found: /home/victor/.ivy2/local/com.lightbend.cinnamon/cinnamon-akka-stream_2.13/2.13.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cinnamon/cinnamon-akka-stream_2.13/2.13.2/cinnamon-akka-stream_2.13-2.13.2.pom
[error] Error downloading com.lightbend.cinnamon:cinnamon-prometheus:2.13.2
[error]   Not found
[error]   Not found
[error]   not found: /home/victor/.ivy2/local/com.lightbend.cinnamon/cinnamon-prometheus/2.13.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cinnamon/cinnamon-prometheus/2.13.2/cinnamon-prometheus-2.13.2.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at lmcoursier.CoursierDependencyResolution$$Lambda$3814/0x000000008838cff8.apply(Unknown Source)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2969/0x0000000078c749e8.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.util.Tracked$$$Lambda$2830/0x00000000740555a0.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2971/0x0000000088033600.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2965/0x000000008802b0f0.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.util.Tracked$$$Lambda$2754/0x0000000070021970.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at sbt.Classpaths$$$Lambda$967/0x000000008448bfc0.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$546/0x0000000078917970.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2626/0x00000000fd724008.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2654/0x00000000fd72c7f0.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2637/0x00000000fd727fb8.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2650/0x00000000fd72a438.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:853)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading com.lightbend.cinnamon:cinnamon-prometheus-httpserver:2.13.2
[error]   Not found
[error]   Not found
[error]   not found: /home/victor/.ivy2/local/com.lightbend.cinnamon/cinnamon-prometheus-httpserver/2.13.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cinnamon/cinnamon-prometheus-httpserver/2.13.2/cinnamon-prometheus-httpserver-2.13.2.pom
[error] Error downloading com.lightbend.cinnamon:cinnamon-akka-stream_2.13:2.13.2
[error]   Not found
[error]   Not found
[error]   not found: /home/victor/.ivy2/local/com.lightbend.cinnamon/cinnamon-akka-stream_2.13/2.13.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cinnamon/cinnamon-akka-stream_2.13/2.13.2/cinnamon-akka-stream_2.13-2.13.2.pom
[error] Error downloading com.lightbend.cinnamon:cinnamon-prometheus:2.13.2
[error]   Not found
[error]   Not found
[error]   not found: /home/victor/.ivy2/local/com.lightbend.cinnamon/cinnamon-prometheus/2.13.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/cinnamon/cinnamon-prometheus/2.13.2/cinnamon-prometheus-2.13.2.pom
